class ImageSettings:
    FONT = "../assets/Perfect DOS VGA 437.ttf"
    TILE_IMAGE_COORDINATES = (1668, 24)
    TILE_IMAGE_TEXT_COORDINATES = (1570, 147)
    TILE_IMAGE_TEXT_COORDINATES_DESCRIPTION = (1570, 178)
    TILE_IMAGE_SCALE = (130, 130)
    TEAM_TEXT_FONT_SIZE = 60
    LEVEL_TEXT_COORDINATES = (55, 25)
    LEVEL_TEXT_FONT_SIZE = 32
    TEAM_NAME_COORDINATES = (0, 50)  # Right aligned, so only Y matters