version: '3.8'
services:
  game_service_api:
    build:
      context: ./game_service_api
      dockerfile: Dockerfile
    volumes:
      - ./game_service_api:/app
    ports:
      - "5000:5000"
    command: ["python", "main.py"]
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongodb:27017/summerbingo
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  discord_bot:
    build: ./discord_bot
    env_file:
      - ./discord_bot/.env
    restart: unless-stopped
volumes:
  mongo_data:
