POST http://localhost:5000/teams
Content-Type: application/json

{
    "team_name": "Winners",
    "discord_channel_id": "00000",
    "players": [
        {
            "discord_id": "2438432823489",
            "runescape_accounts": ["rsn1", "rsn2"]
        },
        {
            "discord_id": "589423983489",
            "runescape_accounts": ["rsn3"]
        }
    ]
}
